name: Build and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate random tag
        id: random-tag
        run: echo "::set-output name=tag::$(echo ${{ github.sha }} | cut -c1-7)"

      - name: Build Docker image
        run: docker build -t dummy-pipeline-image:${{ steps.random-tag.outputs.tag }} .

      - name: Run tests
        id: test
        run: |
          docker run --name dummy-pipeline-container --rm dummy-pipeline-image:${{ steps.random-tag.outputs.tag }} pytest | tee test_logs.txt

      - name: Archive test logs
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: test_logs.txt

      - name: Remove container
        run: docker rm dummy-pipeline-container
